### ISSUE TITLE
After starting Haskelly in Stack "Stack run" buttons don't change on non-stack haskell files

### ISSUE THREAD

**Issue by jpotecki** [martrik/Haskelly#2]
If I open in Haskelly a stack project and then create a single .hs file in a different location, e.g. on the Desktop, then the buttons at the bottom don't change. It should be "QuickCheck" instead of "Stack Test"

**Comment by martrik** [comment]
I will fix this asap.

**Comment by martrik** [comment]
There was a mistake, this wasn't the issue fixed by the commit.
